version: '3.8'

services:

  db:
    image: postgres:latest # Ultima versão do postgres
    restart: on-failure # Sempre quando houver problemas
    environment: # Dados para login
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5555:5432'
    expose:
      - 5432
    volumes:
      - .:/volumes/postgres
    labels:
      - postgres/img
    container_name: postgres-container
    networks:
      applications:
        ipv4_address: 172.20.0.5

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
    labels:
      - adminer/img
    container_name: adminer-container
    volumes:
      - .:/volumes/adminer
    networks:
      applications:
        ipv4_address: 172.20.0.6

networks:
  applications:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
